### ISSUE TITLE
Race condition accessing `todos`

### ISSUE THREAD

**Issue by s-k** [trozware/To-Day#2]
First of all, I liked your blog post about the app! Thank you for that.

I believe the app contains a possible race condition. The `todos` property in `AppState` is accessed from SwiftUI on the main thread. In fact, because it uses `@Published`, it may only be modified from the main thread. However, in `debounceSave()`, you access it from a background thread:

```swift
      DispatchQueue.global(qos: .background).async { [weak self] in
        print("Saving after debounce")
        if let self {
          self.dataStore.saveTodos(todos: self.todos)
        }
      }
```

I believe, this may cause a race condition when `todos` is accessed at the same time it is written by SwiftUI.

**Comment by s-k** [comment]
I believe the code could be made thread-safe like this:

```swift
      DispatchQueue.global(qos: .background).async { [todos, weak self] in
        print("Saving after debounce")
        if let self {
          self.dataStore.saveTodos(todos: todos)
        }
      }
```

**Comment by trozware** [comment]
Thanks Stephen. I had assumed that the debounce would avoid race conditions unless the save took longer than 0.5 seconds, but I'll add your fix into the next release, just in case.

Edit: your suggested fix doesn't build.

**Comment by trozware** [comment]
This version works:

```swift
let task = DispatchWorkItem { [todos, weak self] in
  DispatchQueue.global(qos: .background).async { [weak self] in
    if let self {
      self.dataStore.saveTodos(todos: todos)
    }
  }
}
```

I'll try it for a while and see what happens.

**Comment by trozware** [comment]
Added to version 1.7
